-- MIGRATION: UP
INSERT INTO
    expansion (name, expansion_code, num_cards)
VALUES
    ('Mythical Island', 'A1a', 86);

INSERT INTO
    card (expansion_code, card_number, name, rarity)
VALUES
    ('A1a', 1, 'Exeggcute', '♢'),
    ('A1a', 2, 'Exeggutor', '♢♢'),
    ('A1a', 3, 'Celebi ex', '♢♢♢♢'),
    ('A1a', 4, 'Snivy', '♢'),
    ('A1a', 5, 'Servine', '♢♢'),
    ('A1a', 6, 'Serperior', '♢♢♢'),
    ('A1a', 7, 'Morelull', '♢'),
    ('A1a', 8, 'Shiinotic', '♢♢'),
    ('A1a', 9, 'Dhelmise', '♢♢'),
    ('A1a', 10, 'Ponyta', '♢'),
    ('A1a', 11, 'Rapidash', '♢♢'),
    ('A1a', 12, 'Magmar', '♢♢'),
    ('A1a', 13, 'Larvesta', '♢'),
    ('A1a', 14, 'Volcarona', '♢♢♢'),
    ('A1a', 15, 'Salandit', '♢'),
    ('A1a', 16, 'Salazzle', '♢'),
    ('A1a', 17, 'Magikarp', '♢'),
    ('A1a', 18, 'Gyarados ex', '♢♢♢♢'),
    ('A1a', 19, 'Vaporeon', '♢♢♢'),
    ('A1a', 20, 'Finneon', '♢'),
    ('A1a', 21, 'Lumineon', '♢♢'),
    ('A1a', 22, 'Chewtle', '♢'),
    ('A1a', 23, 'Drednaw', '♢♢'),
    ('A1a', 24, 'Cramorant', '♢'),
    ('A1a', 25, 'Pikachu', '♢'),
    ('A1a', 26, 'Raichu', '♢♢♢'),
    ('A1a', 27, 'Electabuzz', '♢♢'),
    ('A1a', 28, 'Joltik', '♢'),
    ('A1a', 29, 'Galvantula', '♢♢'),
    ('A1a', 30, 'Dedenne', '♢'),
    ('A1a', 31, 'Mew', '♢♢♢'),
    ('A1a', 32, 'Mew ex', '♢♢♢♢'),
    ('A1a', 33, 'Sigilyph', '♢♢'),
    ('A1a', 34, 'Elgyem', '♢'),
    ('A1a', 35, 'Beheeyem', '♢♢'),
    ('A1a', 36, 'Flabébé', '♢'),
    ('A1a', 37, 'Floette', '♢'),
    ('A1a', 38, 'Florges', '♢♢'),
    ('A1a', 39, 'Swirlix', '♢'),
    ('A1a', 40, 'Slurpuff', '♢'),
    ('A1a', 41, 'Mankey', '♢'),
    ('A1a', 42, 'Primeape', '♢'),
    ('A1a', 43, 'Geodude', '♢'),
    ('A1a', 44, 'Graveler', '♢♢'),
    ('A1a', 45, 'Golem', '♢♢♢'),
    ('A1a', 46, 'Aerodactyl ex', '♢♢♢♢'),
    ('A1a', 47, 'Marshadow', '♢♢♢'),
    ('A1a', 48, 'Stonejourner', '♢♢'),
    ('A1a', 49, 'Koffing', '♢'),
    ('A1a', 50, 'Weezing', '♢♢'),
    ('A1a', 51, 'Purrloin', '♢'),
    ('A1a', 52, 'Liepard', '♢'),
    ('A1a', 53, 'Venipede', '♢'),
    ('A1a', 54, 'Whirlipede', '♢'),
    ('A1a', 55, 'Scolipede', '♢♢'),
    ('A1a', 56, 'Druddigon', '♢♢'),
    ('A1a', 57, 'Pidgey', '♢'),
    ('A1a', 58, 'Pidgeotto', '♢'),
    ('A1a', 59, 'Pidgeot ex', '♢♢♢♢'),
    ('A1a', 60, 'Tauros', '♢♢♢'),
    ('A1a', 61, 'Eevee', '♢'),
    ('A1a', 62, 'Chatot', '♢'),
    ('A1a', 63, 'Old Amber', '♢'),
    ('A1a', 64, 'Pokemon Flute', '♢♢'),
    ('A1a', 65, 'Mythical Slab', '♢♢'),
    ('A1a', 66, 'Budding Expeditioner', '♢♢'),
    ('A1a', 67, 'Blue', '♢♢'),
    ('A1a', 68, 'Leaf', '♢♢'),
    ('A1a', 69, 'Exeggutor', '☆'),
    ('A1a', 70, 'Serperior', '☆'),
    ('A1a', 71, 'Salandit', '☆'),
    ('A1a', 72, 'Vaporeon', '☆'),
    ('A1a', 73, 'Dedenne', '☆'),
    ('A1a', 74, 'Marshadow', '☆');

-- MIGRATION: DOWN
DELETE FROM
    expansion
WHERE
    expansion_code = "A1a";
