-- MIGRATION: UP
INSERT INTO
    expansion (name, expansion_code, num_cards)
VALUES
    ('Space-Time Smackdown', 'A2', 207);

INSERT INTO
    card (expansion_code, card_number, name, rarity)
VALUES
    ('A2', 1, 'Oddish', '♢'),
    ('A2', 2, 'Gloom', '♢'),
    ('A2', 3, 'Bellossom', '♢♢'),
    ('A2', 4, 'Tangela', '♢'),
    ('A2', 5, 'Tangrowth', '♢♢'),
    ('A2', 6, 'Yanma', '♢'),
    ('A2', 7, 'Yanmega ex', '♢♢♢♢'),
    ('A2', 8, 'Roselia', '♢'),
    ('A2', 9, 'Roserade', '♢♢'),
    ('A2', 10, 'Turtwig', '♢'),
    ('A2', 11, 'Grotle', '♢♢'),
    ('A2', 12, 'Torterra', '♢♢♢'),
    ('A2', 13, 'Kricketot', '♢'),
    ('A2', 14, 'Kricketune', '♢'),
    ('A2', 15, 'Burmy', '♢'),
    ('A2', 16, 'Wormadam', '♢'),
    ('A2', 17, 'Combee', '♢'),
    ('A2', 18, 'Vespiquen', '♢♢'),
    ('A2', 19, 'Carnivine', '♢♢'),
    ('A2', 20, 'Leafeon', '♢♢♢'),
    ('A2', 21, 'Mow Rotom', '♢'),
    ('A2', 22, 'Shaymin', '♢♢♢'),
    ('A2', 23, 'Magmar', '♢'),
    ('A2', 24, 'Magmortar', '♢♢♢'),
    ('A2', 25, 'Slugma', '♢'),
    ('A2', 26, 'Magcargo', '♢♢'),
    ('A2', 27, 'Chimchar', '♢'),
    ('A2', 28, 'Monferno', '♢♢'),
    ('A2', 29, 'Infernape ex', '♢♢♢♢'),
    ('A2', 30, 'Heat Rotom', '♢'),
    ('A2', 31, 'Swinub', '♢'),
    ('A2', 32, 'Piloswine', '♢♢'),
    ('A2', 33, 'Mamoswine', '♢♢♢'),
    ('A2', 34, 'Regice', '♢♢'),
    ('A2', 35, 'Piplup', '♢'),
    ('A2', 36, 'Prinplup', '♢♢'),
    ('A2', 37, 'Empoleon', '♢♢♢'),
    ('A2', 38, 'Buizel', '♢'),
    ('A2', 39, 'Floatzel', '♢♢'),
    ('A2', 40, 'Shellos', '♢'),
    ('A2', 41, 'Gastrodon', '♢♢'),
    ('A2', 42, 'Finneon', '♢'),
    ('A2', 43, 'Lumineon', '♢♢'),
    ('A2', 44, 'Snover', '♢'),
    ('A2', 45, 'Abomasnow', '♢♢'),
    ('A2', 46, 'Glaceon', '♢♢♢'),
    ('A2', 47, 'Wash Rotom', '♢'),
    ('A2', 48, 'Frost Rotom', '♢'),
    ('A2', 49, 'Palkia ex', '♢♢♢♢'),
    ('A2', 50, 'Manaphy', '♢♢'),
    ('A2', 51, 'Magnemite', '♢'),
    ('A2', 52, 'Magneton', '♢♢'),
    ('A2', 53, 'Magnezone', '♢♢♢'),
    ('A2', 54, 'Voltorb', '♢'),
    ('A2', 55, 'Electrode', '♢♢'),
    ('A2', 56, 'Electabuzz', '♢'),
    ('A2', 57, 'Electivire', '♢♢♢'),
    ('A2', 58, 'Shinx', '♢'),
    ('A2', 59, 'Luxio', '♢♢'),
    ('A2', 60, 'Luxray', '♢♢♢'),
    ('A2', 61, 'Pachirisu ex', '♢♢♢♢'),
    ('A2', 62, 'Rotom', '♢'),
    ('A2', 63, 'Togepi', '♢'),
    ('A2', 64, 'Togetic', '♢♢'),
    ('A2', 65, 'Togekiss', '♢♢♢'),
    ('A2', 66, 'Misdreavus', '♢'),
    ('A2', 67, 'Mismagius ex', '♢♢♢♢'),
    ('A2', 68, 'Ralts', '♢'),
    ('A2', 69, 'Kirlia', '♢'),
    ('A2', 70, 'Duskull', '♢'),
    ('A2', 71, 'Dusclops', '♢♢'),
    ('A2', 72, 'Dusknoir', '♢♢♢'),
    ('A2', 73, 'Drifloon', '♢'),
    ('A2', 74, 'Drifblim', '♢♢'),
    ('A2', 75, 'Uxie', '♢♢'),
    ('A2', 76, 'Mesprit', '♢♢♢'),
    ('A2', 77, 'Azelf', '♢♢'),
    ('A2', 78, 'Giratina', '♢♢♢'),
    ('A2', 79, 'Cresselia', '♢♢♢'),
    ('A2', 80, 'Rhyhorn', '♢'),
    ('A2', 81, 'Rhydon', '♢♢'),
    ('A2', 82, 'Rhyperior', '♢♢♢'),
    ('A2', 83, 'Gligar', '♢'),
    ('A2', 84, 'Gliscor', '♢♢'),
    ('A2', 85, 'Hitmontop', '♢'),
    ('A2', 86, 'Nosepass', '♢'),
    ('A2', 87, 'Regirock', '♢♢'),
    ('A2', 88, 'Cranidos', '♢♢'),
    ('A2', 89, 'Rampardos', '♢♢♢'),
    ('A2', 90, 'Wormadam', '♢'),
    ('A2', 91, 'Riolu', '♢'),
    ('A2', 92, 'Lucario', '♢♢♢'),
    ('A2', 93, 'Hippopotas', '♢'),
    ('A2', 94, 'Hippowdon', '♢♢'),
    ('A2', 95, 'Gallade ex', '♢♢♢♢'),
    ('A2', 96, 'Murkrow', '♢'),
    ('A2', 97, 'Honchkrow', '♢♢'),
    ('A2', 98, 'Sneasel', '♢'),
    ('A2', 99, 'Weavile ex', '♢♢♢♢'),
    ('A2', 100, 'Poochyena', '♢'),
    ('A2', 101, 'Mightyena', '♢♢'),
    ('A2', 102, 'Stunky', '♢'),
    ('A2', 103, 'Skuntank', '♢♢'),
    ('A2', 104, 'Spiritomb', '♢♢'),
    ('A2', 105, 'Skorupi', '♢'),
    ('A2', 106, 'Drapion', '♢♢'),
    ('A2', 107, 'Croagunk', '♢'),
    ('A2', 108, 'Toxicroak', '♢♢'),
    ('A2', 109, 'Darkrai', '♢♢♢'),
    ('A2', 110, 'Darkrai ex', '♢♢♢♢'),
    ('A2', 111, 'Skarmory', '♢♢'),
    ('A2', 112, 'Registeel', '♢♢'),
    ('A2', 113, 'Shieldon', '♢♢'),
    ('A2', 114, 'Bastiodon', '♢♢♢'),
    ('A2', 115, 'Wormadam', '♢'),
    ('A2', 116, 'Bronzor', '♢'),
    ('A2', 117, 'Bronzong', '♢♢'),
    ('A2', 118, 'Probopass', '♢♢'),
    ('A2', 119, 'Dialga ex', '♢♢♢♢'),
    ('A2', 120, 'Heatran', '♢♢♢'),
    ('A2', 121, 'Gible', '♢'),
    ('A2', 122, 'Gabite', '♢♢'),
    ('A2', 123, 'Garchomp', '♢♢♢'),
    ('A2', 124, 'Lickitung', '♢'),
    ('A2', 125, 'Lickilicky ex', '♢♢♢♢'),
    ('A2', 126, 'Eevee', '♢'),
    ('A2', 127, 'Porygon', '♢'),
    ('A2', 128, 'Porygon2', '♢♢'),
    ('A2', 129, 'Porygon-Z', '♢♢♢'),
    ('A2', 130, 'Aipom', '♢'),
    ('A2', 131, 'Ambipom', '♢'),
    ('A2', 132, 'Starly', '♢'),
    ('A2', 133, 'Staravia', '♢'),
    ('A2', 134, 'Staraptor', '♢♢'),
    ('A2', 135, 'Bidoof', '♢'),
    ('A2', 136, 'Bibarel', '♢'),
    ('A2', 137, 'Buneary', '♢'),
    ('A2', 138, 'Lopunny', '♢'),
    ('A2', 139, 'Glameow', '♢'),
    ('A2', 140, 'Purugly', '♢♢'),
    ('A2', 141, 'Chatot', '♢'),
    ('A2', 142, 'Fan Rotom', '♢'),
    ('A2', 143, 'Regigigas', '♢♢♢'),
    ('A2', 144, 'Skull Fossil', '♢'),
    ('A2', 145, 'Armor Fossil', '♢'),
    ('A2', 146, 'Pokemon Communication', '♢♢'),
    ('A2', 147, 'Giant Cape', '♢♢'),
    ('A2', 148, 'Rocky Helmet', '♢♢'),
    ('A2', 149, 'Lum Berry', '♢♢'),
    ('A2', 150, 'Cyrus', '♢♢'),
    ('A2', 151, 'Team Galactic Grunt', '♢♢'),
    ('A2', 152, 'Cynthia', '♢♢'),
    ('A2', 153, 'Volkner', '♢♢'),
    ('A2', 154, 'Dawn', '♢♢'),
    ('A2', 155, 'Mars', '♢♢'),
    ('A2', 156, 'Tangrowth', '☆'),
    ('A2', 157, 'Combee', '☆'),
    ('A2', 158, 'Carnivine', '☆'),
    ('A2', 159, 'Shaymin', '☆'),
    ('A2', 160, 'Mamoswine', '☆'),
    ('A2', 161, 'Gastrodon', '☆'),
    ('A2', 162, 'Manaphy', '☆'),
    ('A2', 163, 'Shinx', '☆'),
    ('A2', 164, 'Rotom', '☆'),
    ('A2', 165, 'Drifloon', '☆'),
    ('A2', 166, 'Mesprit', '☆'),
    ('A2', 167, 'Giratina', '☆'),
    ('A2', 168, 'Cresselia', '☆'),
    ('A2', 169, 'Rhyperior', '☆'),
    ('A2', 170, 'Lucario', '☆'),
    ('A2', 171, 'Hippopotas', '☆'),
    ('A2', 172, 'Spiritomb', '☆'),
    ('A2', 173, 'Croagunk', '☆'),
    ('A2', 174, 'Heatran', '☆'),
    ('A2', 175, 'Garchomp', '☆'),
    ('A2', 176, 'Staraptor', '☆'),
    ('A2', 177, 'Bidoof', '☆'),
    ('A2', 178, 'Glameow', '☆'),
    ('A2', 179, 'Regigigas', '☆');

-- MIGRATION: DOWN
DELETE FROM
    expansion
WHERE
    expansion_code = "A2";
